[workspace]
resolver = "2"

members = [ "integration",
        "samples",
        "samples-loose-types", 
        "ui",
]

default-members = [
        "integration",
        "samples",
        "ui",
]

[profile.test]
lto = "fat"

[profile.dev]
lto = "fat"

[profile.release]
lto = "fat"
