[workspace]
resolver = "2"
members = [
        "integration",
        "samples",
        "samples-loose-types",
]
default-members = [
        "integration",
        "samples",
]

[profile.test]
lto = "fat"

[profile.dev]
lto = "fat"

[profile.release]
lto = "fat"
